name: Solidity
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # Discover all strategies in the project
  strategy-list:
    name: Strategy list
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: echo "matrix=$(ls ./crates/strategies | jq -R -s -c 'split("\n")[:-1]')" >> "$GITHUB_OUTPUT"

  # Matrix across all discovered strategies
  tests:
    runs-on: ubuntu-latest
    needs: [strategy-list]
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.strategy-list.outputs.matrix) }}
    env:
      ETH_MAINNET_HTTP: https://eth-mainnet.alchemyapi.io/v2/Lc7oIGYeL_QvInzI0Wiu_pOZZDEKBrdf
    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Foundry version 
        run: forge --version

      - name: Run ${{ matrix.target }} tests
        run: forge test --root ./crates/strategies/${{ matrix.target }}/contracts
